# Generated by Django 3.2.12 on 2022-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_column="user_id", max_length=255)),
                ("user_name", models.CharField(db_column="user_name", max_length=255)),
                ("email", models.CharField(db_column="email", max_length=255)),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
